### ISSUE TITLE
Encoding then decoding `Option<Vec<u8>>` (and similar) loses `None` and gets `Some([])` instead

### ISSUE THREAD

**Issue by jmesmon** [3Hren/msgpack-rust#41]
A quick repo setup for using serde to demonstrate: https://github.com/jmesmon/rmp-serde-bork/blob/master/src/main.rs.in

I don't know if this reproduces with `rustc-serialize`

**Comment by jmesmon** [comment]
```
     Running target/debug/serde_example-9fd9795ebd0c3c47

running 3 tests
test round_trip_cow ... ok
test round_trip_option ... FAILED
test round_trip_option_cow ... FAILED

failures:

---- round_trip_option stdout ----
	thread 'round_trip_option' panicked at 'assertion failed: `(left == right)` (left: `Foo { it: Some([]) }`, right: `Foo { it: None }`)', /home/cody/C/serde-use-test/target/debug/build/serde_example-874eecc9e8e0cff8/out/main.rs:359


---- round_trip_option_cow stdout ----
	thread 'round_trip_option_cow' panicked at 'assertion failed: `(left == right)` (left: `Foo { it: Some([]) }`, right: `Foo { it: None }`)', /home/cody/C/serde-use-test/target/debug/build/serde_example-874eecc9e8e0cff8/out/main.rs:182



failures:
    round_trip_option
    round_trip_option_cow

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:255
```

**Comment by 3Hren** [comment]
Hmm, that's not good.

I'll take a look in 1-2 days.

Thanks!

**Comment by 3Hren** [comment]
Should be fixed with https://github.com/3Hren/msgpack-rust/pull/44.
